services:
  # main db
  mysql:
    image: mysql:5.7
    volumes:
      - ${ZEEGUU_DATA_FOLDER}/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ZEEGUU_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${ZEEGUU_MYSQL_DB}
      MYSQL_USER: ${ZEEGUU_MYSQL_USER}
      MYSQL_PASSWORD: ${ZEEGUU_MYSQL_USER_PASSWORD}
    networks:
      - zeeguu_backend
    restart: unless-stopped

  # main db
  fmd_mysql:
    image: mysql:5.7
    volumes:
      - ${ZEEGUU_DATA_FOLDER}/fmd_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${FMD_ROOT_PASS}
      MYSQL_DATABASE: ${FMD_MYSQL_DB}
      MYSQL_USER: ${FMD_MYSQL_USER}
      MYSQL_PASSWORD: ${FMD_MYSQL_USER_PASS}
    networks:
      - zeeguu_backend
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0 # is this still needed?
    volumes:
      - ${ZEEGUU_DATA_FOLDER}/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - zeeguu_backend
    restart: unless-stopped

  readability_server:
    image: zeeguu/readability_server
    networks:
      - zeeguu_backend
    restart: unless-stopped

  zapi:
    depends_on:
      - fmd_mysql
      - elasticsearch
      - readability_server
    image: zeeguu/api:latest
    build: .
    ports:
      - "127.0.0.1:8080:8080"
      # to consider mapping only to localhost cf here:
      # https://serverfault.com/questions/681571/docker-exposed-ports-accessible-from-outside-iptables-rules-ignored
      # otherwise the port is visible from the outside; even against ufw rules!
    volumes:
      - .:/Zeeguu-API
      - ${ZEEGUU_DATA_FOLDER}:/zeeguu-data
    #      - ./api.cfg:/Zeeguu-API/api.cfg
    #      - ./fmd.cfg:/Zeeguu-API/fmd.cfg
    #      - ./lu-mir-zeeguu-credentials.json:/Zeeguu-API/lu-mir-zeeguu-credentials.json
    environment:
      ZEEGUU_CONFIG: /Zeeguu-API/api.cfg
      ZEEGUU_DATA_FOLDER: /zeeguu-data/
      SENTRY_DSN: ${SENTRY_DSN}
      FLASK_MONITORING_DASHBOARD_CONFIG: /Zeeguu-API/fmd.cfg
      MICROSOFT_TRANSLATE_API_KEY: ${MICROSOFT_TRANSLATE_API_KEY}
      GOOGLE_TRANSLATE_API_KEY: ${GOOGLE_TRANSLATE_API_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: /Zeeguu-API/lu-mir-zeeguu-credentials.json
      WORDNIK_API_KEY: ${WORDNIK_API_KEY}
      MULTI_LANG_TRANSLATOR_AB_TESTING: ${MULTI_LANG_TRANSLATOR_AB_TESTING}
      ZEEGUU_ES_CONN_STRING: "http://elasticsearch:9200"
      FOLDER_FOR_REPORT_OUTPUT: /zeeguu-data/crawl-reports
      CRAWL_REPORT_DATA: /zeeguu-data/crawl-reports/data

    command: /usr/sbin/apache2ctl -D FOREGROUND
    networks:
      - zeeguu_backend
    restart: unless-stopped

# TODO add the zapi_pink back

networks:
  zeeguu_backend:
